### PR TITLE
Reorganizing scripts under related categories

### PR DESCRIPTION
**Pull request by aditya-uw**
Hey @leewujung I cleaned up my subsampling repository I put my tests under `src/tests`. I feel like I have a better idea than before of how my tests should be so feel free to look at the 3 .py files I have there.  If you want to see the type of IPIs I used for the simulate data. There are figures under `daily_notebook/20231016_test_activity_metric_functions.ipynb` and `daily_notebook/20231016_test_subsampling.ipynb` for seeing the IPI functions.

Apart from that, there is also `bout_clustering.py` that has changed a bit and I would like your review on. 

I wanted to move our discussion to GitHub but all my commits to this repository were direct so I thought I could branch out and create this PR. Let me know if there's a better way!

### CODE REVIEW

**Comment by leewujung** [comment]
I think PR is a good idea. Let's take it in smaller steps -- one thing important is that smaller and focused PRs are easier to review. A PR should also have a summary on the key changes and preferably some background info. You don't have to worry about the background info here since I know what you are working on and why.

I suggest the following:
- change the title to something that is descriptive of the PR content
- add a summary to point me to only the specific modules (.py files) that are relevant to subsampling, and save the other parts for later PRs/discussions
  - mechanistically, for this one you are doing a one-time dump for new code so it is hard to separate, but I am pretty sure there will be changes, likely structural, to other components that I won't be reviewing this time, so I can review those in later PRs

On a quick glance, I also have the following suggestions about organization:
- separate modules into different subpackages under `src`:
  - src/
  - src/bout:
    - bout.py
    - clustering.py: separate out those that are used for clustering here
    - plot.py: all bout-related plotting code
  - core.py can stay at the src level
  - cli.py can stay at the src level
  - src/calls
    - data_handling.py
      - probably better renamed as detection_organization.py or something similar
      - you have some functions that contain only one line: this means you are over-factoring things
    - feature_extraction.py
      - if what's in this module are functions to compute spectrum for each detected calls, then rename is to spectrum.py or similar
  - plotting.py
    - probably can rename to plot.py to make things consistent
    - seeing this, there's a decision here that if you want to have a src/plot directory that contains plotting functions for different things (e.g., src/plot/plot_bout.py, src/plot/plot_detections.py, src/plot/plot_spectrum.py etc), or separate the plotting functions under each of the directories (e.g., src/bout/plot.py, src/spectrum/plot.py, src/detections/plot.py)

Maybe this PR would just be a reorganization PR, and in the next PR we do the subsampling code?

**Comment by aditya-uw** [comment]
Your suggestions sound good! I'm very appreciative (and also incredibly impressed!) that you could figure out all these suggestions from your "quick glance" haha. I'll work on these!

Quick things:
1) Yes `feature_extraction.py` is related to gathering the spectrums of calls and the calls themselves. I'll rename and reorganize it.
2) I think I'll go with the `src/bout/plot.py`, `src/spectrum/plot.py`, and `src/detections/plot.py` suggestion.
3) Yes I think it'll be good to keep this PR specific to reorganization so I can practice making focused PRs.

**Comment by aditya-uw** [comment]
Hi @leewujung, I think I finished reorganizing but I made some changes during implementation to what you suggested.

- I renamed `data_handling.py` to `activity_assembly.py` and put it under `activity` folder. The reason for this is because I feel like the contents relate to how we measure bat activity and assembling data from all the individual bd2 files. `detections` felt too close to the 1 metric where we count # of detections.
- I put `subsampling.py` under `activity` because I'm not sure if it needed its own categorical folder. We also run subsampling on the activity so that's my reasoning.
- I think I removed the one-line functions that were in `data_handling.py` and you're right so thanks!

All the bout scripts were reorganized just as you suggested!

**Review by leewujung — APPROVED** [review]
Awesome! Feel free to merge.

**Pull request merged**
